name: List Directories

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Web sandbox'
        required: true
        default: 'web-sandbox'

jobs:
  list_directories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Directories
        run: |
          cd ${{ github.workspace }}
          find . -type d -not -path '*/\.*' -print
